function PlotXY( foldername, filename, frames)
%PLOTS Use this to go through plots generated by TraCKer_2D_subplot
%   Folder name should be of the format 'folderpath\foldername\'
%   The second input allows you to start in the middle of the file in case
%   you need to stop at some point. The function should output the place
%   you stopped.
dum = ls(foldername);
names = dum((3:size(dum,1)),:);

for j=1:frames
    IMG(:,:,j) = imread(filename,'Index',j);
end
MEAN = mean(IMG,3);

for i = 1:size(names,1)
    filenames = strcat(foldername, '\', names(i,:));
    data{i} = textread(filenames,'','delimiter',','); %#ok<DTXTRD>
end
for j = 1:frames
    for k = 1:size(names,1)
    x(j,k) = data{k}(j,2);
    y(j,k) = data{k}(j,3);
    end
end
save('xandy.mat','x','y');
figure;
        imshow(-MEAN,[]);
        hold on;
        colors='brgycm';
        for i = 1:size(names,1)
            j=6-mod(i,6);
            plot(x(~isnan(x(:,i)),i)/160,y(~isnan(x(:,i)),i)/160,colors(j),'linewidth',2);
        end
        
end
