function i = Plots( tifname, foldername, varargin )
%PLOTS Use this to go through plots generated by TraCKer_2D_subplot
%   Folder name should be of the format 'folderpath\foldername\'
%   The second input allows you to start in the middle of the file in case
%   you need to stop at some point. The function should output the place
%   you stopped.
dum = ls(foldername);
names = dum((3:size(dum,1)),:);

new_foldername = strcat(foldername(1:end-1),'_trimmed');
if ~exist(new_foldername,'dir')
    mkdir(new_foldername);
end

k = 0;
if nargin == 2
    i = 0;
else
    i = varargin{1};
end

while (k~=4 && i < size(names,1))
    i = i+1;
    filename = strcat(foldername, names(i,:));
    data = textread(filename,'','delimiter',','); %#ok<DTXTRD>
    x = data(~isnan(data(:,2)),2)/160;
    y = data(~isnan(data(:,2)),3)/160;
    z = mean(data(~isnan(data(:,2)),4))/(300*.7)/12;
    figure('units','normalized','outerposition',[0 0 1 1]);
    axh = subplot(1,2,1);
    plot(data(:,1),data(:,5),'b-');
    hold on;
    plot(data(~isnan(data(:,2)),1),data(~isnan(data(:,2)),5),'r.','MarkerSize',16);
    hold off;
    title('Click and drag from point to point to select a peak.');
    subplot(1,2,2)
    imagesc(imread(tifname, find(data(:,5)==max(data(:,5)),1,'first')))
    hold on
    quiver(x(1:end-1), y(1:end-1) ,(x(2:end)-x(1:end-1)), (y(2:end)-y(1:end-1)), 0, 'MaxHeadSize', 0.5, 'Color', 'k' , 'LineWidth', 3);
    title(sprintf('%f',z));
    %xlim([min(x)-100 max(x)+100])
    %ylim([min(y)-100 max(y)+100])
    pause(.2); %this performs magic. accept it without question.
    rect = getrect(axh);
    pause(.2); %this performs magic. accept it without question.
    if rect(3)<1
        k = 3;
    else
        f = figure('units','normalized','outerposition',[0 0 1 1],...
            'WindowKeyPressFcn',@wkpcb);
        directions = sprintf([...
            'D or %s: Accepts input and goes to next \n\n ' ...
            'A or %s: Rejects input to try again \n\n ' ...
            'S or %s: Rejects input and goes to next \n\n ' ...
            'W or %s: Exits the program, returning index of last viewed'],...
            '\rightarrow','\leftarrow','\downarrow','\uparrow');
        text(0.5,0.5,directions,...
            'VerticalAlignment','Middle',...
            'HorizontalAlignment','Center',...
            'Units','normalized',...
            'FontSize',18);
        waitfor(f);
        if (k == 1)
            first = find(data(:,1) == round(rect(1)));
            last = find(data(:,1) == round(rect(1)+rect(3)));
            new_data = data(first:last,:);
            new_path = sprintf('%s\\%s',new_foldername,names(i,:));
            csvwrite(new_path,new_data);
            clear new_data;
        elseif (k == 2 || k == 4)
            i = i - 1;
        end
    end
    close all;
end

    function wkpcb(~, evt)
        c_num = double(evt.Character);
        switch(c_num)
            case {29,100} % right arrow or 'd'
                k = 1; % Accepts input and goes to next
            case {28,97} % left arrow or 'a'
                k = 2; % Rejects input to try again
            case {31,115} % down arrow or 's'
                k = 3; % Rejects input and goes to next
            case {30,119} % up arrow or 'w'
                k = 4; % Exits the program, returning index of last viewed
        end
        close(f);
    end

end